### ISSUE TITLE
How to know if JasperPHP::process()->execute() is finish or not ?

### ISSUE THREAD

**Issue by Devidia** [cossou/JasperPHP#32]
Hello,

There is a way to know if execution of JasperPHP::process()->execute()  is finish or not ?

Because my script stream the pdf file before the execution ending, I hacked this with a sleep() method but it's so tricky and not usefull.

```

public function printPlanFormation($id)
    {
        $af_print = ActionFormation::find($id);

        $x = array('driver' => 'mysql','username' => Config::get('database.connections.mysql.username'),'password' => Config::get('database.connections.mysql.password'),'host' => Config::get('database.connections.mysql.host'),'database' => Config::get('database.connections.mysql.database'));

            $y = array("planformation_id" => $af_print->plan_formation_id,'stagiaire_id' => $af_print->stagiaire_id,'REPORT_DIR' => base_path() .'/storage/reporting/');

            JasperPHP::process(
                base_path() . '/storage/reporting/hrm_plan_formation.jasper', //Input file
                base_path() . '/storage/reporting/hrm_plan_formation', //Output file without extension
                array("pdf"), //Output format
                $y, //Parameters array
                $x //DB connection array
            )->execute();
            $file = base_path() .'/storage/reporting/hrm_plan_formation.pdf';

            sleep(9); // <============ hack

            if (file_exists($file)) {
                header('Content-Description: File Transfer');
                header('Content-Type: application/pdf');
                header('Content-Disposition: attachment; filename='.basename($file));
                ob_clean();
                flush();
                return readfile($file);
            }
    }
```

**Comment by cossou** [comment]
Hi @Devidia 

I never run into synchronisation issues before. 
The execution function should not return before the PDF is generated.

Did you manage to solve it?

Regards

**Comment by lexDevidia** [comment]
hi.
the real problem is online I have to use the php sleep() function before get the good generated PDF file.
I don't want to use the sleep function because the execution time increases.
It's work in localhost without the sleep function, and I need to make it work online too without the sleep() function.

Can you help me?

**Comment by lexDevidia** [comment]
hi.
the real problem is online I have to use the php sleep() function before get the good generated PDF file.
I don't want to use the sleep function because the execution time increases.
It's work in localhost without the sleep function, and I need to make it work online too without the sleep() function.

Can you help me?

**Comment by cossou** [comment]
Has I said before. I never run into issues. When the function ends the PDF is created and can be returned. Not sure how can the function returns before the shell command is executed.

**Comment by Devidia** [comment]
Well,

Many thanks for your answers.

Have you got any idea how to know when the function end in order to continue our logic ?


Cheers,

**Comment by jdiefenbach83** [comment]
Hello guys, I'm facing the same issue. How Can I help you to fix it?

Thx

**Comment by jdiefenbach83** [comment]
Guys, I could fix it out! It's simple. You need set the "background" parameter in "process" method to false. This way it will work fine.

@lexDevidia You can check what I said in the code below

First the method signature:
```
public function process(
$input_file, 
$output_file = false, 
$format = array("pdf"), 
$parameters = array(), 
$db_connection = array(), 
$background = true, 
$redirect_output = true)
```
Second, my code:

```
$jr = new JasperPHP(TMP);             
$ds = $this->Capa->getDataSource();        
$jr->process(
            TMP . 'extrato.jasper',
            TMP . 'extrato_siscoserv_' . $id,            
            array('pdf'),
            array(                
                'capa_id' => $id
            ),
            array(
                'driver' => 'mysql', //Aqui é por causa do Java                
                'host' => $ds->config['host'],
                'port' => $ds->config['port'],
                'database' => $ds->config['database'],                
                'username' => $ds->config['login'],
                'password' => $ds->config['password']
            ),
            false
        )->execute();
```

PS: I am using CakePHP 2.8.1, because that I couldn't use Static methods. Instead I should to instanced an object.

Cheers

**Comment by Devidia** [comment]
Many thanks for your help !
